# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title BayesMVP_internal
#' @description
#' Run a SUR Bayesian sampler -- internal function
#' @name BayesMVP_internal
#' @param dataFile path to data file
#' @param outFilePath path to where the output is to be written
#' @param nIter number of iterations
#' @param nChains number of parallel chains to run
#'
#' NOTE THAT THIS IS BASICALLY JUST A WRAPPER
NULL

BayesMVP_internal <- function(dataFile, mrfGFile, blockFile, structureGraphFile, hyperParFile, outFilePath, nIter = 10L, burnin = 0L, nChains = 1L, covariancePrior = "HIW", gammaPrior = "hotspot", gammaSampler = "bandit", gammaInit = "MLE", betaPrior = "independent", maxThreads = 1L, tick = 1000L, output_gamma = TRUE, output_beta = TRUE, output_Gy = TRUE, output_sigmaRho = TRUE, output_pi = TRUE, output_tail = TRUE, output_model_size = TRUE, output_CPO = TRUE, output_model_visit = FALSE) {
    .Call('_BayesMVP_BayesMVP_internal', PACKAGE = 'BayesMVP', dataFile, mrfGFile, blockFile, structureGraphFile, hyperParFile, outFilePath, nIter, burnin, nChains, covariancePrior, gammaPrior, gammaSampler, gammaInit, betaPrior, maxThreads, tick, output_gamma, output_beta, output_Gy, output_sigmaRho, output_pi, output_tail, output_model_size, output_CPO, output_model_visit)
}

randU01 <- function() {
    .Call('_BayesMVP_randU01', PACKAGE = 'BayesMVP')
}

randLogU01 <- function() {
    .Call('_BayesMVP_randLogU01', PACKAGE = 'BayesMVP')
}

randIntUniform <- function(a, b) {
    .Call('_BayesMVP_randIntUniform', PACKAGE = 'BayesMVP', a, b)
}

randExponential <- function(lambda) {
    .Call('_BayesMVP_randExponential', PACKAGE = 'BayesMVP', lambda)
}

randVecExponential <- function(n, lambda) {
    .Call('_BayesMVP_randVecExponential', PACKAGE = 'BayesMVP', n, lambda)
}

randBinomial <- function(n, p) {
    .Call('_BayesMVP_randBinomial', PACKAGE = 'BayesMVP', n, p)
}

randMultinomial <- function(n, prob) {
    .Call('_BayesMVP_randMultinomial', PACKAGE = 'BayesMVP', n, prob)
}

randNormal <- function(m = 0., sigmaSquare = 1.) {
    .Call('_BayesMVP_randNormal', PACKAGE = 'BayesMVP', m, sigmaSquare)
}

randVecNormal <- function(n, m = 0., sigmaSquare = 1.) {
    .Call('_BayesMVP_randVecNormal', PACKAGE = 'BayesMVP', n, m, sigmaSquare)
}

randT <- function(nu) {
    .Call('_BayesMVP_randT', PACKAGE = 'BayesMVP', nu)
}

randVecT <- function(n, nu) {
    .Call('_BayesMVP_randVecT', PACKAGE = 'BayesMVP', n, nu)
}

randMvT <- function(nu, m, Sigma) {
    .Call('_BayesMVP_randMvT', PACKAGE = 'BayesMVP', nu, m, Sigma)
}

randGamma <- function(shape, scale) {
    .Call('_BayesMVP_randGamma', PACKAGE = 'BayesMVP', shape, scale)
}

randIGamma <- function(shape, scale) {
    .Call('_BayesMVP_randIGamma', PACKAGE = 'BayesMVP', shape, scale)
}

randWishart <- function(df, S) {
    .Call('_BayesMVP_randWishart', PACKAGE = 'BayesMVP', df, S)
}

randBeta <- function(a, b) {
    .Call('_BayesMVP_randBeta', PACKAGE = 'BayesMVP', a, b)
}

randBernoulli <- function(pi) {
    .Call('_BayesMVP_randBernoulli', PACKAGE = 'BayesMVP', pi)
}

